# Generated by Django 6.0.7 on 2026-08-30 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop POS'), ('android', 'Android CEO app')], max_length=10)),
                ('name', models.CharField(blank=True, help_text='e.g. "Front counter PC", "CEO\'s phone"', max_length=150)),
                ('app_version', models.CharField(blank=True, max_length=30)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.shop')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
