# Generated by Django 6.0.7 on 2026-08-30 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('branch_code', models.CharField(blank=True, help_text='Unique within the organization, e.g. "WUSE001".', max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=10)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=50)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('tax_rate_default', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('enterprise_until', models.DateTimeField(blank=True, help_text='If set and in the future, every branch under this org has cloud services enabled regardless of its own individual subscription.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The CEO — organization-wide access to every branch. NOT the same as a branch-level Worker(role="owner"), which is scoped to one branch only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
