# Generated by Django 6.0.7 on 2026-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_type',
            field=models.CharField(choices=[('gadgets', 'Gadgets & electronics (phones, laptops, accessories)'), ('clothing', 'Clothing & fashion'), ('pharmacy', 'Pharmacy & health products'), ('general', 'General retail / other')], default='general', help_text='Set once at signup. Drives which optional modules (like Repairs) are shown.', max_length=20),
        ),
    ]
