# Generated by Django 6.0.7 on 2026-09-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo_url',
            field=models.URLField(blank=True, help_text="Hosted image URL (e.g. from an image host) — printed at the top of receipts and shown in the desktop app once downloaded at login. Not a file upload field: this backend has no persistent media storage configured (Railway's filesystem is ephemeral), so a URL to an already-hosted image is the reliable option here.", max_length=500),
        ),
    ]
