# Generated by Django 6.0.7 on 2026-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shop_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='receipt_footer_note',
            field=models.CharField(blank=True, help_text="Custom closing line printed at the bottom of this branch's receipts (e.g. a return policy or a thank-you message), replacing the generic default. Set from Settings -> Receipt, usually right after signup. Thermal (Android) receipts print this as plain text; the web/desktop invoice prints it the same way — neither renders a logo image from this field, that's what logo_url is for.", max_length=200),
        ),
    ]
