# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='last_event_sequence',
            field=models.BigIntegerField(
                default=0,
                help_text='Monotonic counter for realtime.RealtimeEvent — incremented under a row '
                          'lock each time an event is broadcast for this shop (see '
                          'realtime.events.broadcast), so every event gets a gapless, per-shop '
                          "sequence number a client can compare against its own last-seen value to "
                          "tell whether it missed anything.",
            ),
        ),
    ]
