# Generated by Django 6.0.7 on 2026-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Admin'), ('branch_manager', 'Branch manager'), ('seller', 'Seller (can log in and sell)'), ('technician', 'Service technician'), ('attendant', 'Shop attendant'), ('other', 'Other')], default='attendant', max_length=20),
        ),
    ]
