# Generated by Django 6.0.7 on 2026-09-27 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rolepermission'),
        ('staff', '0002_alter_worker_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Admin'), ('branch_manager', 'Branch manager'), ('seller', 'Seller (can log in and sell)'), ('reception', 'Receptionist'), ('technician', 'Service technician'), ('attendant', 'Shop attendant'), ('other', 'Other')], default='attendant', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('half_day', 'Half day'), ('on_leave', 'On leave')], default='present', max_length=10)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('marked_by', models.ForeignKey(blank=True, help_text='Who recorded this entry — usually reception, sometimes an owner/manager correcting one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to='staff.worker')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.shop')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.worker')),
            ],
            options={
                'ordering': ['-date', 'worker__full_name'],
                'constraints': [models.UniqueConstraint(fields=('worker', 'date'), name='unique_attendance_per_worker_per_day')],
            },
        ),
    ]
