# Generated by Django 6.0.7 on 2026-08-30 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.UUIDField()),
                ('operation', models.CharField(max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to='core.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'entity_type', 'entity_id'], name='sync_syncop_shop_id_881216_idx')],
            },
        ),
    ]
