# Generated by Django 6.0.7 on 2026-09-29 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_rolepermission'),
        ('staff', '0003_alter_worker_role_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('is_default', models.BooleanField(default=False, help_text='True for one of the seeded starter categories — informational only, never affects behavior; a default category can be renamed or deleted exactly like a custom one.')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.shop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('pos', 'POS/Card')], default='cash', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('time', models.TimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, help_text='Cloudinary-hosted photo of the receipt/document — optional. Same pattern as InventoryItem.image_url; only ever set through the dedicated `receipt` upload action.', max_length=500, null=True)),
                ('receipt_public_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to='staff.worker')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.shop')),
                ('category', models.ForeignKey(help_text='PROTECT, not SET_NULL/CASCADE: a category in use cannot be hard-deleted out from under historical expenses — see ExpenseCategoryViewSet.perform_destroy, which deactivates instead.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_expense_category_name_per_shop'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['shop', 'date'], name='expenses_ex_shop_id_b0a6b4_idx'),
        ),
    ]
