# Generated by Django 6.0.7 on 2026-09-29 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rolepermission'),
        ('liabilities', '0001_initial'),
        ('staff', '0003_alter_worker_role_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiabilityPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('pos', 'POS/Card')], default='cash', max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddField(
            model_name='liability',
            name='cleared_at',
            field=models.DateTimeField(blank=True, help_text='When status last became "cleared".', null=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities_created', to='staff.worker'),
        ),
        migrations.AddField(
            model_name='liability',
            name='owed_to',
            field=models.CharField(blank=True, help_text='Who or which company this is owed to.', max_length=200),
        ),
        migrations.AlterField(
            model_name='liability',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The original amount owed — never edited after creation; see class docstring.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liability',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('cleared', 'Cleared')], default='unpaid', help_text='Maintained automatically from `payments` by refresh_status() — not meant to be set directly by a client; see LiabilityPaymentViewSet.', max_length=15),
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['shop', 'status'], name='liabilities_shop_id_242d6f_idx'),
        ),
        migrations.AddField(
            model_name='liabilitypayment',
            name='liability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='liabilities.liability'),
        ),
        migrations.AddField(
            model_name='liabilitypayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_payments_recorded', to='staff.worker'),
        ),
        migrations.AddField(
            model_name='liabilitypayment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.shop'),
        ),
        migrations.AddIndex(
            model_name='liabilitypayment',
            index=models.Index(fields=['shop', 'paid_at'], name='liabilities_shop_id_410dce_idx'),
        ),
    ]
