# Generated by Django 6.0.7

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_shop_last_event_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.BigIntegerField(help_text='Per-shop monotonic order — see core.Shop.last_event_sequence.')),
                ('event_type', models.CharField(help_text='e.g. "sale.created", "inventory.updated".', max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_events', to='core.shop')),
            ],
            options={
                'ordering': ['shop', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='realtimeevent',
            index=models.Index(fields=['shop', 'sequence'], name='realtime_re_shop_id_a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeevent',
            index=models.Index(fields=['created_at'], name='realtime_re_created_d4e5f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='realtimeevent',
            constraint=models.UniqueConstraint(fields=('shop', 'sequence'), name='unique_shop_event_sequence'),
        ),
    ]
