# Generated by Django 6.0.7 on 2026-08-30 23:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.CharField(blank=True, help_text='Short label e.g. "Para500"', max_length=40)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Scanned/printed barcode (UPC/EAN or a shop-assigned code). Null (not empty string) when unset so multiple barcode-less products never collide on the unique constraint.', max_length=64, null=True, unique=True)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('part', 'Part'), ('accessory', 'Accessory'), ('consumable', 'Consumable'), ('other', 'Other')], default='other', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='PIECE', help_text='e.g. TABLET, PIECE, BOX, PACK', max_length=30)),
                ('spec', models.CharField(blank=True, help_text='e.g. 200mg, 15.6-inch', max_length=100)),
                ('min_stock', models.PositiveIntegerField(default=2, help_text='Reorder alert threshold')),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current default unit selling price (kept in sync with the latest batch, editable)', max_digits=12)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.shop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('batch_number', models.CharField(max_length=60)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, help_text='Fallback if no linked Supplier record', max_length=200)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventoryitem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.shop')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
    ]
