# Generated by Django 6.0.7 on 2026-09-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='prescription_required',
            field=models.BooleanField(default=False, help_text='Pharmacy shops only — flags a drug that legally cannot be sold without a prescription. Harmless (and hidden in the UI) for every other business type.'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('part', 'Part'), ('accessory', 'Accessory'), ('consumable', 'Consumable'), ('medicine', 'Medicine / Drug'), ('tablet_capsule', 'Tablet / Capsule'), ('syrup_liquid', 'Syrup / Liquid'), ('injection', 'Injection'), ('medical_supply', 'Medical supply'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
