# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_prescription_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('part', 'Part'), ('accessory', 'Accessory'), ('consumable', 'Consumable'), ('medicine', 'Medicine / Drug'), ('tablet_capsule', 'Tablet / Capsule'), ('syrup_liquid', 'Syrup / Liquid'), ('injection', 'Injection'), ('medical_supply', 'Medical supply'), ('equipment', 'Equipment'), ('apparel_top', 'Top / Shirt'), ('apparel_bottom', 'Trousers / Skirt'), ('footwear', 'Footwear'), ('outerwear', 'Outerwear'), ('clothing_accessory', 'Bag / Fashion accessory'), ('grocery', 'Grocery'), ('household', 'Household item'), ('stationery', 'Stationery'), ('beverage', 'Beverage'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
