# Generated by Django 6.0.7

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_category_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('sku', models.CharField(blank=True, help_text='Optional variant-specific code, e.g. for its own barcode label', max_length=60)),
                ('is_active', models.BooleanField(default=True, help_text='Retire a discontinued variant without losing its sale history')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.inventoryitem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.shop')),
            ],
            options={
                'ordering': ['size', 'color'],
            },
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='variant',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches',
                to='inventory.itemvariant',
                help_text="Which size/color this stock is for, on an item that has variants. Left null for an "
                          "item with none — unchanged from how batches worked before variants existed.",
            ),
        ),
        migrations.AddConstraint(
            model_name='itemvariant',
            constraint=models.UniqueConstraint(fields=('item', 'size', 'color'), name='unique_variant_per_item'),
        ),
    ]
