# Generated by hand to match the project's existing migration style
# (see 0002_inventoryitem_prescription_required_and_more.py) -- adds the
# optional product-image fields. Both fields are nullable/blank with safe
# defaults, so this is a pure additive migration: every existing product
# row simply gets image_url=NULL, cloudinary_public_id='' and keeps
# working exactly as before.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemvariant_stockbatch_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image_url',
            field=models.URLField(
                blank=True, max_length=500, null=True,
                help_text='Cloudinary-hosted product photo URL. Null when no image has been uploaded -- a '
                           'perfectly normal, fully-supported state, not an error or an incomplete product.',
            ),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cloudinary_public_id',
            field=models.CharField(
                blank=True, max_length=255,
                help_text='Cloudinary asset id backing image_url -- needed to replace/delete the asset later. '
                           'Internal bookkeeping only; never exposed on the public serializer.',
            ),
        ),
    ]
