# Generated by Django 6.0.7 on 2026-08-30 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enterprise', models.BooleanField(default=False)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=10)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace period'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', help_text='Manual floor — set to e.g. "suspended" to force-cut cloud services regardless of dates.', max_length=10)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='When the current paid period ends. Blank = no expiry enforced (e.g. a comped org).', null=True)),
                ('grace_period_days', models.PositiveIntegerField(default=3, help_text='Days after current_period_end before cloud services actually cut off.')),
                ('auto_renew', models.BooleanField(default=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('amount_kobo', models.PositiveIntegerField()),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('period_end_after', models.DateTimeField(help_text='What current_period_end became once this was applied.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.organization')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
