# Generated by Django 6.0.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('inventory', '0004_itemvariant_stockbatch_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items',
                to='inventory.itemvariant',
                help_text='Which size/color was sold, when the item has variants. Left null for an item with none.',
            ),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='variant_label',
            field=models.CharField(blank=True, help_text='Snapshot of the variant (e.g. "Medium / Blue") at time of sale', max_length=100),
        ),
    ]
