# Generated by Django 6.0.7 on 2026-09-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='stock_shortfall',
            field=models.PositiveIntegerField(default=0, help_text="How many of `quantity` could NOT be matched to real stock batches at allocation time — 0 means the sale is fully backed by tracked stock. Non-zero means two tills (or a till and the web) oversold the same item before either knew about the other's sale: this many units were rung up and paid for but had no batch left to deduct from. The sale itself is never blocked or rolled back over this — the customer already has the item, physically, by the time this is computed — this field exists purely so the shortfall is recorded and visible (reports, realtime alert) instead of silently absorbed into a slightly-wrong unit_cost with no trace at all. See _allocate_stock in sales/views.py."),
        ),
    ]
